# NOTE:
# This pipeline requires a secret 'PLATFORM_REPO_UPDATE_PAT' set up in the GitHub secrets.
# The secret's value should be a PAT token with the permissions to push to the repository's main branch.

name: '.Platform: Update ReadMe Module Tables'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'arm/**/deploy.bicep'
      - 'arm/**/deploy.json'

env:
  pipelinePrincipalGitUserName: 'CARMLPipelinePrincipal'
  pipelinePrincipalGitUserEmail: 'CARML@noreply.github.com'

jobs:
  job_update_readme:
    runs-on: ubuntu-20.04
    name: 'Update module tables'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: '${{ secrets.PLATFORM_REPO_UPDATE_PAT }}' # Sets general GIT credentials up
      - name: 'Update general ReadMe'
        shell: pwsh
        run: |
          # Load used functions
          . "$env:GITHUB_WORKSPACE/utilities/tools/Set-ReadMeModuleTable.ps1"

          $functionInput = @{
            ModulesPath    = Join-Path $env:GITHUB_WORKSPACE 'arm'
            FilePath       = Join-Path $env:GITHUB_WORKSPACE 'README.md'
            Organization   = ($env:GITHUB_REPOSITORY).split('/')[0]
            RepositoryName = ($env:GITHUB_REPOSITORY).split('/')[1]
            ColumnsInOrder = @('Name', 'Status')
            SortByColumn   = 'Name'
            Environment    = 'GitHub'
          }

          Write-Verbose "Invoke task with" -Verbose
          Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose

          Set-ReadMeModuleTable @functionInput -Verbose

      - name: 'Update module folder ReadMe'
        shell: pwsh
        run: |
          # Load used functions
          . "$env:GITHUB_WORKSPACE/utilities/tools/Set-ReadMeModuleTable.ps1"

          $functionInput = @{
            ModulesPath    = Join-Path $env:GITHUB_WORKSPACE 'arm'
            FilePath       = Join-Path $env:GITHUB_WORKSPACE 'arm/README.md'
            Organization   = ($env:GITHUB_REPOSITORY).split('/')[0]
            RepositoryName = ($env:GITHUB_REPOSITORY).split('/')[1]
            ColumnsInOrder = @('Name', 'ProviderNamespace','ResourceType')
            Environment    = 'GitHub'
          }

          Write-Verbose "Invoke task with" -Verbose
          Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose

          Set-ReadMeModuleTable @functionInput -Verbose

      - name: 'Push changes'
        shell: pwsh
        run: |
          git config --global user.email '${{ env.pipelinePrincipalGitUserEmail }}'
          git config --global user.name '${{ env.pipelinePrincipalGitUserName }}'

          git pull
          git add .
          git commit -m "Push updated Readme file(s)"
          git push
